apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sprint-expense-cluster      # you can rename if you want
  region: us-east-1

managedNodeGroups:
  - name: ng-demo
    instanceTypes: ["t3.small"]
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
